# Generated by Django 3.1.4 on 2021-01-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210111_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('nigeria', 'nigeria'), ('ghana', 'ghana'), ('kenya', 'kenya'), ('uk', 'uk')], default='nigeria', max_length=16),
        ),
    ]
