# Generated by Django 3.1.4 on 2021-01-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='jumga_commission',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='rider_commission',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='seller_commission',
            field=models.BigIntegerField(default=0),
        ),
    ]
