# Generated by Django 3.1.4 on 2021-01-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210118_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='delivery_fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
