# Generated by Django 3.1.4 on 2021-01-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_productsinorder_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='total_cost',
            field=models.BigIntegerField(default=0),
        ),
    ]
