# Generated by Django 3.1.4 on 2021-01-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210118_1322'),
        ('rider', '0004_auto_20210115_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.productsinorder'),
        ),
    ]
