version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
    environment:
      - USE_DOCKER=True

    hostname: server

  website:
    build: ./client-website
    volumes:
      - ./client-website:/usr/src/app
    ports:
      - "3000:3000"
    hostname: website
  app:
    build: ./client-app
    volumes:
      - ./client-app:/usr/src/app
    ports:
      - "3001:3001"
    hostname: app
