# Generated by Django 3.1.4 on 2021-01-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210106_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rider', 'rider'), ('seller', 'seller'), ('admin', 'admin'), ('superuser', 'superuser'), ('buyer', 'buyer')], default='seller', max_length=16),
        ),
    ]
