# Generated by Django 3.1.4 on 2021-01-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn',
            field=models.BigIntegerField(default=0),
        ),
    ]
