# Generated by Django 3.1.4 on 2021-01-13 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
